### ISSUE TITLE
TypeError while using reconstruct method 

### ISSUE THREAD

**Issue by AnkDos** [shobhit99/ReconstructPdf#1]
Here is how I initialised the class :

```
from reconpdf import ReconstructPdf
ob = ReconstructPdf()
fi = open('/home/ankur/http_ser/merge_corrupt.pdf', 'rb')
ob.reconstruct(fi)

```
Here is the traceback : 

```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ankur/Desktop/reconpdf.py", line 115, in reconstruct
    self.append(pdf_file)
  File "/home/ankur/Desktop/reconpdf.py", line 69, in append
    if "/Length" not in self.header_buffer.getvalue():
TypeError: a bytes-like object is required, not 'str'
```

**Comment by shobhit99** [comment]
@AnkDos Please try with python2.7
